---
apiVersion: v1
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'severity', 'namespace']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'dingding.webhook1'
      routes:
        - receiver: 'dingding.webhook1'
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 30m
          match:
            team: SRE
    receivers:
    - name: 'dingding.webhook1'
      webhook_configs:
      - url: 'http://1.1.1.1:8060/dingtalk/webhook1/send'
    - name: 'dingding.webhook.all'
      webhook_configs:
      - url: 'http://1.1.1.1:8060/dingtalk/webhook_mention_all/send'
        send_resolved: true
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager 
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30003
  selector:
    app: alertmanager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alertmanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - args:
        - --volume-dir=/etc/alertmanager
        - --webhook-url=http://127.0.0.1:9093/-/reload
        image: breaklinux/configmap-reload:v0.5.0 
        imagePullPolicy: IfNotPresent
        name: alertmanager-configmap-reload
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: config
      - args:
        - --cluster.advertise-address=0.0.0.0:9093
        - --config.file=/etc/alertmanager/alertmanager.yml
        image: breaklinux/alertmanager:v0.21.0 
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: alertmanager
        ports:
        - containerPort: 9093
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: alertmanager
        name: config
