apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: k8s-developer-devops-python

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s:k8s-developer-devops-python:view
subjects:
- kind: User
  name: system:serviceaccount:default:k8s-developer-devops-python
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s:k8s-developer-devops-python
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods/exec # 查看日志需要访问该资源
  verbs:
  - get
  - watch
  - list
  - create

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s:k8s-developer-devops-python
subjects:
- kind: User
  name: system:serviceaccount:default:k8s-developer-devops-python
roleRef:
  kind: ClusterRole
  name: k8s:k8s-developer-devops-python
  apiGroup: rbac.authorization.k8s.io

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devops-python
  name: k8s:k8s-developer-devops-python
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s:k8s-developer-devops-python
  namespace: devops-python
subjects:
- kind: User
  name: system:serviceaccount:default:k8s-developer-devops-python
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: k8s:k8s-developer-devops-python
  apiGroup: rbac.authorization.k8s.io

